name: Lightdim
options:
  bundleIdPrefix: com.shimondeitel.lightexposurelog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Lightdim:
    type: application
    platform: iOS
    sources:
      - path: Lightdim
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.lightexposurelog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Lightdim/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  LightdimTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: LightdimTests
      - path: Lightdim.storekit
    dependencies:
      - target: Lightdim
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.lightexposurelog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  LightdimUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: LightdimUITests
    dependencies:
      - target: Lightdim
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.lightexposurelog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Lightdim:
    build:
      targets:
        Lightdim: all
        LightdimTests: [test]
        LightdimUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Lightdim.storekit
    test:
      config: Debug
      storeKitConfiguration: Lightdim.storekit
      targets:
        - LightdimTests
        - LightdimUITests
    archive:
      config: Release
